//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSWeb.WCF.DataAccess.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public long Id_Application { get; set; }
        public string Name { get; set; }
    }
}
